Nama : Syifa Nur Nabila


NIM : 2023071017


Mata Kuliah : Desain dan Analisis Algoritma (INF-A)

In [1]:
#Menampilkan Lists (Struktur data dalam python)
aList = ["John", 33,"Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [2]:
#Latihan membuat Lists
import datetime as dt
tanggal = dt.date.today()
Mahasiswa = ["Syifa Nur Nabila","2023071017","Informatika","Desain dan Analisis Algoritma", str(tanggal), "Universitas Pembangunan Jaya"]
print(Mahasiswa)

['Syifa Nur Nabila', '2023071017', 'Informatika', 'Desain dan Analisis Algoritma', '2024-09-19', 'Universitas Pembangunan Jaya']


In [99]:
#Menampilkan Lists index
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [4]:
#Latihan mencetak NIM dan Kampus dengan memanggil urutan indeks dalam list
print("NIM", Mahasiswa[1])
print("Kampus", Mahasiswa[5])

NIM 2023071017
Kampus Universitas Pembangunan Jaya


In [101]:
#Menampilkan rentang color menggunakan Slicing
bin_colors[0:2]

['Red', 'Green']

In [102]:
#Menampilkan rentang color menggunakan Slicing
bin_colors[1:22]

['Green', 'Blue', 'Yellow']

In [6]:
#Latihan menampilkan NIM dan Prodi menggunakan Slicing
Mahasiswa[1:3]

['2023071017', 'Informatika']

In [ ]:
#Latihan menampilkan Mata Kuliah dan Tanggal menggunakan Slicing
print("Mata Kuliah Tanggal Berapa?", Mahasiswa[3:5])

Mata Kuliah Tanggal Berapa? ['Desain dan Analisis Algoritma', datetime.date(2024, 9, 19)]


In [7]:
#Membuat iterasi (pengulangan) serta menampilkan seluruh data color dan menambahkan kata Square
for aColor in bin_colors:
  print (aColor + " Square ")

Red Square 
Green Square 
Blue Square 
Yellow Square 


In [8]:
#Latihan menampilkan isi list Mahasiswa dan menambahkan kata (UPJ) diawal kalimat
for aMahasiswa in Mahasiswa:
  print('UPJ ' + aMahasiswa )

UPJ Syifa Nur Nabila
UPJ 2023071017
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ 2024-09-19
UPJ Universitas Pembangunan Jaya


In [9]:
#Membuat Tuple dan Menampilkan rentang color urutan ke-1
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [10]:
#Menampilkan data Tuple rentang color urutan ke-2 sampai terakhir
bin_colors[2:]


('Blue', 'Yellow')

In [11]:
#Latihan membuat Tuple
tup_UPJ = ("Universitas", "Pembangunan", "Jaya")
tup_UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [12]:
#Membuat Nested Tuple
hariAwal = ("senin","selasa","rabu")
hariAkhir = ("kamis","jumat","sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [13]:
#Latihan membuat Tuple bersarang
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [14]:
#Membuat dan menampilkan Dictionary
bin_colors ={
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"
}
print(bin_colors)


{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [15]:
#Menampilkan Dictionary menggunakan fungsi get
bin_colors.get('approved_color')
bin_colors['approved_color']


'Green'

In [16]:
#Memperbarui nilai dictionary yang terkait dengan key
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [17]:
#Menampilkan list key dan value
Mhs ={
"Nama": "Syifa Nur Nabila",
"NIM": "2023071017",
"Prodi": "Informatika",
"Universitas": "UPJ"
}
print(Mhs)

{'Nama': 'Syifa Nur Nabila', 'NIM': '2023071017', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [103]:
# Membuat Tuple acak berisi nilai boolean, dictionary dan list
# Mendefinisikan tuple dengan tipe data acak
acak = (True, {'name': 'depotkode', 'status': 'alive'}, [1, 2, 3])

# Mencetak setiap elemen dari tuple
print("Tuple contains:")
for item in acak:
    print(item)

Tuple contains:
True
{'name': 'depotkode', 'status': 'alive'}
[1, 2, 3]


In [22]:
#Membuat dan menampilkan data Sets
green = {'grass', 'leaves'}
print(green)


{'leaves', 'grass'}


In [23]:
#Jika mencoba menambahkan elemen redudan (duplikat) maka program akan mengabaikannya
green = {'grass', 'leaves','leaves'}
print(green)


{'leaves', 'grass'}


In [ ]:
#Inisiasi Set
set_01 = {4,5,6,2}
print(set_01)


{2, 4, 5, 6}


In [24]:
#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)


<class 'set'>
{1, 2, 3, 4}


In [30]:
#Percobaan: Jika Kode berikut dijalankan akan menghasilkan error karena set tidak mendukung akses elemen menggunakan indeks, set adalah tipe data yang tidak berurutan.
set_01 = {4,5,6,2}
print(set_03[1])

TypeError: 'set' object is not subscriptable

In [31]:
# Menambahkan anggota set dapat dilakukan dengan menggunakan metode add()
set_04 = {2, 3, 4, 5, 6}
set_04.add(1)
print(set_04)

{1, 2, 3, 4, 5, 6}


In [32]:
# Set tidak memiliki indeks, sehingga elemen tidak bisa diubah langsung. Namun, elemen bisa dihapus dan ditambahkan kembali. Contoh: mengganti 4 dengan 10.
set_04 = {1, 2, 3, 4, 5, 6, 7, 8}
set_04.discard(4)  # hapus nilai 4
print(set_04)

set_04.add(10)  # menambahkan nilai 10
print(set_04)

{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


In [49]:
#Union set
set_A = {1,2,3,4}
set_B = {3,4,5,6}
print(set_A|set_B)
print(set_A.union(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [51]:
#Membuat Intersection / Irisan Set

print(set_A & set_B)
print(set_A.intersection(set_B))

{3, 4}
{3, 4}


In [54]:
#Difference set operasi mencari perbedaan anggota dari dua buah set atau lebih.
#A-B
print(set_A - set_B)
print(set_A.difference(set_B))
#B-A
print(set_B - set_A)
print(set_B.difference(set_A))


{1, 2}
{1, 2}
{5, 6}
{5, 6}


In [55]:
#Symmetric Difference adalah semua anggota pada set A dan B dikurangi dengan anggota yang berada pada dua set tersebut.
print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [33]:
#Latihan membuat Union Set
yellow={'dandelions', 'leaves', 'fire hydrant'}
red={'leaves', 'fire hydrant', 'rose', 'blood'}
uni= yellow.union(red)
inter= yellow.intersection(red)
print(uni)
print(inter)



{'blood', 'fire hydrant', 'rose', 'dandelions', 'leaves'}
{'leaves', 'fire hydrant'}


In [34]:
#Latihan membuat Union Set menggunakan cara yg berbeda
yellow={'dandelions', 'leaves', 'fire hydrant'}
red={'leaves', 'fire hydrant', 'rose', 'blood'}
uni= yellow.union(red)
inter= yellow.intersection(red)
print(yellow|red)
print(yellow&red)



{'blood', 'fire hydrant', 'rose', 'dandelions', 'leaves'}
{'leaves', 'fire hydrant'}


In [39]:
#Latihan Membuat Intersection / Irisan Set

#Menentukan set_yellow and set_red
set_yellow = yellow
set_red = red

print(set_yellow & set_red)
print(set_yellow.intersection(set_red))



{'leaves', 'fire hydrant'}
{'leaves', 'fire hydrant'}


In [44]:
# Latihan membuat Difference set, operasi mencari perbedaan anggota dari dua buah set atau lebih.
print(set_yellow - set_red)
print(set_yellow.difference(set_red))

print(set_red - set_yellow)
print(set_red.difference(set_yellow))

{'dandelions'}
{'dandelions'}
{'rose', 'blood'}
{'rose', 'blood'}


In [46]:
#Latihan membuat Symmetric Difference, yaitu semua anggota pada set A dan B dikurangi dengan anggota yang berada pada dua set tersebut.
print(set_yellow ^ set_red)
print(set_yellow.symmetric_difference(set_red))

{'blood', 'rose', 'dandelions'}
{'blood', 'rose', 'dandelions'}


In [63]:
# Membuat DataFrames
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]
    ], columns=['id', 'name', 'age', 'decision'])

print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [60]:
#Memilih kolom-kolom tertentu dari sebuah DataFrame.
df[['name','age','decision']]


name  age  decision
0   Fares   32      True
1   Elena   23     False
2  Steven   40      True

In [65]:
#Membuat seleksi kolom
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [66]:
#Membuat seleksi kolom
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
# Row selection
df.iloc[1:3,:]


id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [67]:
#Row selection
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [70]:
#Row selection
df[(df.age < 35) & (df.decision == True)]

id   name  age  decision
0  1  Fares   32      True

In [72]:
#Memberikan index label seperti pada series
import pandas as pd

# Membuat data dalam bentuk dictionary
data = {'satu': [1, 1, 1, 1, 1],
        'dua': [2, 2, 2, 2, 2],
        'tiga': [3, 3, 3, 3, 3]}

# Membuat DataFrame dengan index yang ditentukan
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df.head())

   satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3


In [74]:
#Latihan membuat DataFrame bernama (Mhs)
import pandas as pd
data = {
    'No': [1, 2, 3],
    'Prodi': ['Informatika', 'Sistem Informasi', 'Teknik Sipil'],
    'Mahasiswa': [50, 55, 40],
    'Laki-laki': [30, 30, 30],
    'Perempuan': [20, 25, 10]
      }

df = pd.DataFrame(data)
print(df)

   No             Prodi  Mahasiswa  Laki-laki  Perempuan
0   1       Informatika         50         30         20
1   2  Sistem Informasi         55         30         25
2   3      Teknik Sipil         40         30         10


In [84]:
#Membuat Matriks

import numpy as np

myMatriks = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatriks)
print(type(myMatriks))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [85]:
#Membuat Transpose Matriks
import numpy as np
matriksC = np.array([[1,2,3],
		     [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [86]:
#Latihan membuat Matriks dan Transpose Matriks
import numpy as np
#Membuat matriks
matriks = np.array([[100, 200, 300],
                   [700, 600, 500],
                   [900, 1000, 800]])
print("Matriks asli:")
print(matriks)

# Melakukan transpose matriks
transpose_matriks = np.transpose(matriks)
print("\nTranspose matriks:")
print(transpose_matriks)

Matriks asli:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose matriks:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [87]:
#Membuat Tipe Data Abstrak: Vector
# Membuat vektor menggunakan list
myVector = [22, 33, 44, 55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [89]:
#Membuat Tipe Data Abstrak: Vector
# Membuat vektor menggunakan Numpy array
import numpy as np
myVector = np.array([22, 33, 44, 55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [91]:
#Membuat Tipe Data Abstrak: Stack
class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            return None

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        else:
            return None

    def size(self):
        return len(self.items)

# Membuat objek stack
stack = Stack()

# Menambahkan elemen ke stack (push)
stack.push("Red")
stack.push("Green")
stack.push("Blue")
stack.push("Yellow")

# Mengambil elemen teratas (pop)
print(stack.pop())  # Output: Yellow

# Mengecek apakah stack kosong
print(stack.is_empty())  # Output: False

# Melihat elemen teratas tanpa menghapusnya (peek)
print(stack.peek())  # Output: Blue

# Mengetahui ukuran stack (setelah menambahkan elemen dan mengambil satu elemen,maka ukuran tumpukan (stack) berkurang)
print(stack.size())

Yellow
False
Blue
3


In [95]:
#Membuat Tipe Data Abstrak Queue
class Queue:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            return None

    def size(self):
        return len(self.items)

# Membuat objek queue
queue = Queue()

# Menambahkan elemen ke queue (enqueue)
queue.enqueue("Red")
queue.enqueue("Green")
queue.enqueue("Blue")
queue.enqueue("Yellow")

# Mengambil elemen terdepan (dequeue)
print(queue.dequeue())
print(queue.dequeue())

# Mengecek ukuran queue (setelah dua kali pengambilan elemen menggunakan dequeue)
print(queue.size())

Red
Green
2


In [96]:
#Membuat Binary Tree dengan Python
class Node:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.data = data

    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print(self.data),
        if self.right:
            self.right.PrintTree()

# Membuat pohon biner sesuai diagram
root = Node(2)
root.left = Node(3)
root.right = Node(5)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(11)
root.right.right = Node(13)

# Mencetak pohon biner
root.PrintTree()

7
3
9
2
11
5
13
